spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: beluga
    password: qwer1234
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jwt:
    secret: secrettestsecrettestsecrettestsecrettestsecrettestsecrettestsecrettestsecrettestsecrettestsecrettest
springdoc:
  show-login-endpoint: true

